appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: sG/H0x4hjohyKYuF4rNeJqbozzkVzqSgq+UFLCMkQC37aPuDoFkkbJF546TimOssV3XXemKXFN7lXQcdztkk+H+G96mpUTyQGIqeRgoylXRJbPppIXJka/gv10kNMKEACoxqfVu+XMiEE/A1+d2mn+It2gn4UjFsZUPFTz0EzoiYsBBucOcjcVKAxUeBBMpGW5GuwIx7lOurk0D6eOzLAw7SAoDCtNAMJPVvtnGTa8zvNLmPjqgMvGnsrk7Ifagb1rgA2jEnt6nOgEo5AKidiJpaJJ5CT3lBx4WIbLD7FCDaU7qGDn/kP28H/s6qEY605T2fpdfGQ/Vp5FR5DCXsOKy2lQ6jCEi6TrGN6eCMvRd08WN1Kx0MI1XOFFpuzp5yqX/qfw9eLuSKPasRra6QQOLt493n0AsiS5pLzI7oCXHh+quCCMOmVVaMEq/UDRniUwUNLtRDHP/j3eHVt1ZbaA0u1ei4WG5VXMRu0J1xPHWzBLAz5O1baIRCxeocyZFm4Xk8NXe/c7VTFlUAZ/X36DcmilD/vlbsUwFSke9ozYY9svS0RIqsxV9FDzGCo57C3KqgKUIQdWuj8uuPp9R8YDhViVbtQJ6b97OH2eVg9G1g/ZfqrTU+KbkHMTHD94S+m7hcg1G9lCkvSXq89nKKtm1d5KVf/Ay2QvPUS4CsdTU=}
conda_forge_output_validation: true
